import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import {ClerkProvider, } from '@clerk/nextjs'
import { Poppins } from "next/font/google";

const inter = Poppins({ subsets: ["latin"], weight:["400", "500","600","700","800","900"] });

export const metadata: Metadata = {
  title: "Collage Hub",
  description: "Generated by Collage Hub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>{children}
        <Toaster />
      </body>
    </html>
  </ClerkProvider>
  );
}
