import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {
  ClerkProvider, 
} from '@clerk/nextjs'
export const metadata: Metadata = {
  title: "Collage Hub",
  description: "Generated by Collage Hub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body> 
        {children}
        <ToastContainer theme="dark"  />
      </body>
    </html>
  </ClerkProvider>
  );
}
