name: Docker Image deployment

on:
  push:
    branches: [ "main" ]
   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build --tag visxxal/collagehub:$(date +%s)
    - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker push visxxal/collagehub:$(date +%s)

