name: Docker Image deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in  
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Build image
    - name: Build the Docker image
      run: |
        IMAGE_TAG="visxxal/collagehub:$(date +%s)"
        docker build --tag $IMAGE_TAG .

    # Push image
    - name: Push the Docker image
      run: |
        IMAGE_TAG="visxxal/collagehub:$(date +%s)"
        docker push $IMAGE_TAG

    # Logout
    - name: Logout from Docker Hub
      run: docker logout
