name: Docker Image deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Define image tag
      run: echo "IMAGE_TAG=visxxal/collagehub:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build --tag "$IMAGE_TAG" .

    - name: Push the Docker image
      run: docker push "$IMAGE_TAG"

    - name: Logout from Docker Hub
      run: docker logout
